packages:
  - .
  - docs

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - nanoid@3.3.18
blockExoticSubdeps: true
strictDepBuilds: true

allowBuilds:
  es5-ext@0.10.64: false
  esbuild@0.28.1: true
  simple-git-hooks@2.13.1: false
  vue-demi@0.14.10: true
